import type { Stage } from '@/lib/types';

/** Stages are content units, not calendar months. No deadlines anywhere. */
export const stages: Stage[] = [
  {
    n: 1,
    title: 'Python where it matters, and the backend gaps',
    outcome:
      'Build, test, containerise and deploy a typed, async Python API with Postgres and pgvector behind it.',
    note: 'Deliberately small. You already have Python basics and SQL — every module has a self-check so you can skip what you know.',
    modules: [
      { id: 's1.1', stage: 1, title: 'Python for AI code', priority: 'core',
        selfCheck: 'Skip this if you can write a decorator that times a function, explain what yield does, use a context manager, and read a type-hinted signature with Optional and generics.' },
      { id: 's1.2', stage: 1, title: 'Pydantic v2', priority: 'core',
        note: 'The most important module in this stage. Pydantic is the type system of the whole AI ecosystem.' },
      { id: 's1.3', stage: 1, title: 'Async Python', priority: 'core' },
      { id: 's1.4', stage: 1, title: 'Tooling and testing', priority: 'core' },
      { id: 's1.5', stage: 1, title: 'FastAPI', priority: 'core' },
      { id: 's1.6', stage: 1, title: 'Postgres conversion', priority: 'core',
        note: 'You know MySQL. This is only the differences, plus the parts AI work needs.' },
      { id: 's1.7', stage: 1, title: 'Docker and local infrastructure', priority: 'core' },
      { id: 's1.8', stage: 1, title: 'AI intuition — the cheap 8 hours', priority: 'core',
        note: 'Conceptual only. No maths homework. Stop when you can explain each one to a friend in two minutes.' },
    ],
    projects: ['p-1.1', 'p-1.2'],
    readiness: [
      'A FastAPI endpoint that streams SSE while making several concurrent async calls with a cap — written without looking things up',
      'You can explain what pydantic is doing when validation fails, and why that error is useful',
      'docker compose up brings up your stack on a clean machine',
      'A pgvector table with an HNSW index exists, and you know what ef_search changes',
      'Tokens, embeddings and temperature — explainable without notes',
    ],
  },
  {
    n: 2,
    title: 'LLM APIs and production prompting',
    outcome:
      'Build a reliable, streaming, cost-instrumented LLM feature against any of the three major providers, with structured output you can trust.',
    modules: [
      { id: 's2.1', stage: 2, title: 'What an LLM call actually is', priority: 'core', topicCount: 6 },
      { id: 's2.2', stage: 2, title: 'Streaming, end to end', priority: 'core', topicCount: 5,
        note: 'Your advantage starts here — every project streams.' },
      { id: 's2.3', stage: 2, title: 'Production prompt engineering', priority: 'core', topicCount: 8 },
      { id: 's2.4', stage: 2, title: 'Structured output you can trust', priority: 'core', topicCount: 5 },
      { id: 's2.5', stage: 2, title: 'Reliability and cost', priority: 'core', topicCount: 6 },
      { id: 's2.6', stage: 2, title: 'Multimodal basics', priority: 'optional', topicCount: 3 },
    ],
    projects: ['p-2.1', 'p-2.2'],
    readiness: [
      'One interface, three providers, same feature',
      'Cancelling a stream actually stops upstream billing, provable in logs',
      'You can state what one request costs, from your own instrumentation',
      'Killing the primary provider key degrades gracefully instead of 500-ing',
      'A prompts/ directory with versions; any output traces back to a version',
      'You have hit five distinct prompt failure modes and know what fixed each',
    ],
  },
  {
    n: 3,
    title: 'RAG for real, and how to know it works',
    outcome:
      'Build retrieval over a messy real corpus, measure its quality with numbers, and improve those numbers deliberately.',
    opener: {
      title: 'Start by auditing the RAG project you already built',
      body: 'Run it against twelve questions about ingestion, chunking, retrieval and measurement. Most will have no answer yet. That list is this stage. And your existing project becomes version 1 — the first row of the results table in p-3.1.',
    },
    modules: [
      { id: 's3.1', stage: 3, title: 'The retrieval problem, properly', priority: 'core', topicCount: 3 },
      { id: 's3.2', stage: 3, title: 'Embeddings in practice', priority: 'core', topicCount: 5 },
      { id: 's3.3', stage: 3, title: 'Ingestion — the unglamorous 60%', priority: 'core', topicCount: 6 },
      { id: 's3.4', stage: 3, title: 'Chunking', priority: 'core', topicCount: 7 },
      { id: 's3.5', stage: 3, title: 'Vector storage', priority: 'core', topicCount: 5 },
      { id: 's3.8', stage: 3, title: 'Evaluation', priority: 'core', topicCount: 7,
        note: 'Comes before the optimisation work on purpose. Build the ruler first.' },
      { id: 's3.6', stage: 3, title: 'Retrieval quality: hybrid, reranking, query understanding', priority: 'core', topicCount: 6 },
      { id: 's3.7', stage: 3, title: 'Context assembly', priority: 'core', topicCount: 5 },
    ],
    projects: ['p-3.1', 'p-3.2'],
    readiness: [
      'A hand-written golden set in the repo',
      'The eval suite runs in CI and you have watched it fail a deliberately bad change',
      'A before/after table: 6+ variants with recall@5, faithfulness, p95, ₹ per query',
      'You can argue RAG vs long context vs fine-tuning from your own numbers',
      'A hand error-analysis of 20 failures, grouped into categories',
      'You can separate how much hybrid search helped from how much reranking helped',
    ],
  },
  {
    n: 4,
    title: 'Tool use, agents, and MCP',
    outcome:
      'Build an agent that takes real actions safely, and publish an MCP server other people’s AI tools can use.',
    modules: [
      { id: 's4.1', stage: 4, title: 'Tool calling, deeply', priority: 'core', topicCount: 6 },
      { id: 's4.2', stage: 4, title: 'The agent loop', priority: 'core', topicCount: 5,
        note: 'Hand-written, no framework. About sixty lines.' },
      { id: 's4.3', stage: 4, title: 'Memory and state', priority: 'core', topicCount: 4 },
      { id: 's4.4', stage: 4, title: 'Orchestration patterns', priority: 'core', topicCount: 5 },
      { id: 's4.5', stage: 4, title: 'One framework: LangGraph', priority: 'core', topicCount: 4 },
      { id: 's4.6', stage: 4, title: 'MCP', priority: 'core', topicCount: 5 },
      { id: 's4.7', stage: 4, title: 'Agent safety and interface', priority: 'core', topicCount: 5 },
    ],
    projects: ['p-4.1', 'p-4.2'],
    readiness: [
      'Your own agent loop, hand-written, with budget enforcement and loop detection',
      'The same agent in LangGraph with Postgres checkpointing, resumable mid-run',
      'An MCP server a stranger can install in one command',
      'An approval gate that survives a server restart',
      'An agent eval suite over 30+ scenarios, pass rate reported honestly',
      'You can explain MCP vs A2A, and why multi-agent is usually the wrong default',
    ],
  },
  {
    n: 5,
    title: 'AI system design, operations, and security',
    outcome:
      'Design, deploy, observe and defend a real AI system — with the dashboards and incident write-ups to prove it.',
    modules: [
      { id: 's5.1', stage: 5, title: 'AI system design as a discipline', priority: 'core', topicCount: 4 },
      { id: 's5.2', stage: 5, title: 'Serving architecture', priority: 'core', topicCount: 5 },
      { id: 's5.3', stage: 5, title: 'Caching, cost and routing', priority: 'core', topicCount: 5 },
      { id: 's5.4', stage: 5, title: 'Observability', priority: 'core', topicCount: 5 },
      { id: 's5.5', stage: 5, title: 'Evaluation as engineering', priority: 'core', topicCount: 5 },
      { id: 's5.6', stage: 5, title: 'Security', priority: 'core', topicCount: 5 },
      { id: 's5.7', stage: 5, title: 'Deployment and CI/CD', priority: 'core', topicCount: 5 },
      { id: 's5.8', stage: 5, title: 'Fine-tuning: when, not how', priority: 'optional', topicCount: 3 },
    ],
    projects: ['p-5.1', 'p-5.2', 'p-5.3'],
    readiness: [
      'One system on AWS or GCP, in containers, with CI/CD',
      'Tracing across all three projects, and a cost dashboard you can screenshot',
      'A CI eval gate blocking merges, demonstrated',
      'A load-test report with a real p95 and a documented breaking point',
      'Cost measurably reduced through caching and routing — you know the number',
      'Eight system designs whiteboarded out loud, two recorded and watched back',
      'OWASP LLM Top 10 reviewed against your own code, with real fixes committed',
      'One written postmortem',
    ],
  },
  {
    n: 6,
    title: 'Capstone and portfolio',
    outcome: 'Three flagship systems, and you are interviewing.',
    modules: [
      { id: 's6.1', stage: 6, title: 'Capstone — AI hiring copilot (you name it)', priority: 'core', topicCount: 4 },
      { id: 's6.2', stage: 6, title: 'One specialisation', priority: 'core', topicCount: 3 },
      { id: 's6.3', stage: 6, title: 'Portfolio', priority: 'core', topicCount: 4 },
      { id: 's6.4', stage: 6, title: 'Interview preparation', priority: 'core', topicCount: 4 },
      { id: 's6.5', stage: 6, title: 'Applications as a pipeline', priority: 'core', topicCount: 2 },
    ],
    projects: ['p-6.1'],
    readiness: [
      'Capstone live, multi-tenant, real users, with a tenant-isolation test',
      'Three flagship projects with architecture docs, numbers and demo videos',
      'GitHub, LinkedIn and site consistent and evidence-led',
      'Twelve mock system designs, some with another person',
      'Applications out, pipeline tracked',
    ],
  },
  {
    n: 7,
    title: 'Interviews, depth, optionality',
    outcome: 'Offers — and a body of work that compounds either way.',
    modules: [
      { id: 's7.1', stage: 7, title: 'Interview execution and same-day debriefs', priority: 'core', topicCount: 3 },
      { id: 's7.2', stage: 7, title: 'Depth on demand', priority: 'core', topicCount: 3 },
      { id: 's7.3', stage: 7, title: 'Optional deep dives: voice, vLLM, GraphRAG, computer use', priority: 'optional', topicCount: 4 },
      { id: 's7.4', stage: 7, title: 'Negotiation and screening a role for real AI work', priority: 'core', topicCount: 2 },
    ],
    projects: ['p-7.1'],
    readiness: [
      'Every round debriefed in writing the same day',
      'Each exposed gap closed before the next round',
    ],
  },
];
